### ISSUE TITLE
Backlog of Test Cases for Reminder and Meeting

### ISSUE THREAD

**Issue by sebastiantoh** [AY2021S1-CS2103T-T11-1/tp#60]
- [x] `commands/reminder/AddCommand`
- [x] `commands/reminder/DeleteCommand`
- [x] `commands/reminder/ListCommand`
- [x] `commands/meeting/AddCommand`
- [x] `commands/meeting/DeleteCommand`
- [x] `commands/meeting/ListCommand`
- [x] `parser/reminder/AddCommandParser`
- [x] `parser/reminder/DeleteCommandParser`
- [x] `parser/reminder/ReminderCommandsParser`

**Comment by AaronnSeah** [comment]
Could you rename it to be more specific to meetings/ reminders? cause title seems general

**Comment by sebastiantoh** [comment]
Done in #114
