### ISSUE TITLE
Chat box text does not wrap

### ISSUE THREAD

**Issue by jmleong666** [AY2021S1-CS2103T-T11-1/tp#98]
**Summary**
Text overflows instead of wrapping after exceeding window width.

**Steps to reproduce**
Enter `contact add` command to trigger the usage message.

**Expected Result**
Text wraps according to window width.

**Actual Result**
Text on the same line overflows without regard to window width.

**Preview**
![ui-bug](https://user-images.githubusercontent.com/65291543/95871686-83accb00-0da0-11eb-965a-5df25cafe05e.png)

**Comment by AaronnSeah** [comment]
I will work on this tomorrow
